# Generated by Django 3.2.5 on 2023-10-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='予定タイトル')),
                ('start_date', models.DateTimeField(verbose_name='イベント開始時間')),
                ('end_date', models.DateTimeField(verbose_name='イベント終了時間')),
                ('last_update', models.DateField(auto_now=True, verbose_name='最終更新時間')),
                ('content', models.TextField(verbose_name='イベント概要')),
                ('period', models.CharField(choices=[('LEGEND FC', 'legend'), ('SCHOOL', 'school')], max_length=50, verbose_name='イベントカテゴリ')),
                ('url', models.URLField(blank=True, null=True, verbose_name='LINK用')),
            ],
        ),
        migrations.CreateModel(
            name='NewslPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('image1', models.ImageField(upload_to='photo1', verbose_name='イメージ画像1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photo1', verbose_name='イメージ画像2')),
                ('category', models.CharField(choices=[('LEGEND FC', 'legend'), ('SCHOOL', 'school')], max_length=50, verbose_name='カテゴリ')),
                ('place', models.CharField(choices=[('船橋市運動公園体育館', 'funabashi'), ('国府台体育館', 'konodai'), ('東部スポーツ体育館', 'tobu'), ('市川市塩浜体育館', 'ichikawa'), ('柏井小学校体育館', 'kashiwai')], max_length=50, verbose_name='会場')),
                ('cost', models.CharField(max_length=20, verbose_name='金額')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル')),
                ('category', models.CharField(choices=[('LEGEND FC', 'legend'), ('SCHOOL', 'school')], max_length=50, verbose_name='カテゴリ')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
        ),
        migrations.CreateModel(
            name='ResultPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=200, verbose_name='相手チーム名')),
                ('category', models.CharField(choices=[('LEGEND FC', 'legend'), ('SCHOOL', 'school')], max_length=50, verbose_name='カテゴリ')),
                ('myresult', models.CharField(max_length=10, verbose_name='自チームの得点')),
                ('oppresult', models.CharField(max_length=10, verbose_name='相手チームの得点')),
                ('posted_at', models.DateField(auto_now_add=True, verbose_name='投稿日')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoOnlyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photo2', verbose_name='イメージ画像1')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footsal.photopost')),
            ],
        ),
        migrations.CreateModel(
            name='SPOP',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('footsal.photoonlypost',),
        ),
        migrations.CreateModel(
            name='SPP',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('footsal.photopost',),
        ),
    ]
